### ISSUE TITLE
Invoice not sent

### ISSUE THREAD

**Issue by jmmmagalhaes** [Katamaze/WHMCS-Free-Action-Hooks#1]
When the quote is accepted, the invoice is created but it is not sented to the client
---regarding "Accept Quote without Logging In" hook ---

**Comment by Kian987** [comment]
It's not a bug but just the way it works. Anyway sending the *Invoice Created* email makes a lot of sense so I'll add this feature asap. Thanks for suggestion :+1:

**Comment by Kian987** [comment]
The hook now sends *Invoice Created* email. You can get the updated version of the script [here](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/hooks/AcceptQuoteWithoutLogin.php).
