### ISSUE TITLE
Question, how to make it work for 5 differentes products ids

### ISSUE THREAD

**Issue by altomarketing** [Katamaze/WHMCS-Free-Action-Hooks#2]
Should i repeat the hook for every product id ? 
or you can modify the script to add severals products id numbers ?

Thanks !!

**Comment by Kian987** [comment]
There are more that 30 action hooks. Which one are you referring to?

**Comment by altomarketing** [comment]
Sorry , i did not realize that the issue was not related with the php file.

**Client to Group based on Purchased Product/Service**

**Comment by Kian987** [comment]
That's a very good point. I'm going to update the hook so that it works with an array of products instead of just one. I'll let you know when it's ready.

**Comment by Kian987** [comment]
I improved the script ever further.

From now on it lets you define group/product pairs. This way you can assign customers to client groups based on multiple products/services. You can find all details [here](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/README.md#client-to-group-based-on-purchased-productservice).

**Comment by altomarketing** [comment]
Excellent, i will test it but one last question.

We give a free _autoaccept order_ product like free hosting
Teorically = Will this hook run before or after the welcome email whmcs message ?

Because we send different logos up to client group like 
`  <img src="https://www.MYWEBSITE.com/assets/img/logos/{$client_group_name}-logo.png"  style="margin-left:auto;margit-right:auto;" id="headerImage" alt="{$client_group_name}" />`

**Comment by Kian987** [comment]
It wouldn't work as `AcceptOrder` hook point triggers when the `Welcome Email` has been sent already. The solution is to use `EmailPreSend` instead. I created an [alternative version](https://github.com/Katamaze/WHMCS-Free-Action-Hooks#client-to-group-based-on-purchased-productservice) that should work as you expect.

**Comment by altomarketing** [comment]
You rocks
