### ISSUE TITLE
About Promotion Code in Email Template

### ISSUE THREAD

**Issue by altomarketing** [Katamaze/WHMCS-Free-Action-Hooks#3]
About The following hook add coupon code to the invoice recepit (if a promo has been applied).

How can i make it work for all Invoice Payment Confirmation ? not only if a promo has been applied

**Comment by Kian987** [comment]
What do you mean? The [hook](https://github.com/Katamaze/WHMCS-Free-Action-Hooks#promotion-code-in-email-template) in question includes promotion details in `Invoice Payment Confirmation`. What do are you trying to achieve?

**Comment by altomarketing** [comment]
You created this hook to indicate to the person who paid what promotion was included in their payment.

I want to notify all customers (all emails _Invoice Payment Confirmation_ mails) , to list all current promotions or discount coupons, not only to those invoices that used coupons.

**Comment by Kian987** [comment]
Got it :+1:

Of course that hook will not work. I'll code a new one as soon as I have free time.

**Comment by Kian987** [comment]
I need further clarification.

> I want to notify all customers (all emails Invoice Payment Confirmation mails) , **to list all current promotions or discount coupons**, not only to those invoices that used coupons.

Let's say a customer has product X (promo applied) and Y. I need to understand what are you trying to do between the following:

- The customer renews product Y. `Invoice Payment Confirmation` reminds him that product X has a promo
- Every time a customer sends a payment the email must list all your existing copuon codes
- None of the above :sweat_smile: please, provide me a detailed example

**Comment by altomarketing** [comment]
this: _Every time a customer sends a payment the email must list all your existing copuon codes_

**Comment by Kian987** [comment]
You can find the hook [here](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/README.md#promotions-array-in-email-templates).

**Comment by altomarketing** [comment]
1 bug:

It shows all promotions even they are expired

**Comment by altomarketing** [comment]
One collaboration: as cupon codes are not clear to what applies, we will use private cupon Notes to detail it:

`<h2>💰 Promos: <strong>🎁</strong>:</h2>
<p>{if $promotions}    {foreach from=$promotions item=promo}</p>
<p>• Promo Description: <em>{$promo.notes}</em><br /> <strong>Use in the cart</strong>: {$promo.code} 👉<strong> to get</strong>: ({if $promo.type == 'Percentage'}{$promo.value}% discount{elseif $promo.type == 'Fixed Amount'}{$promo.value} € descuento {elseif $promo.type == 'Price Override'}Precio Especial{$promo.value} €{elseif $promo.type == 'Free Setup'}Free Setup{/if})</p>
<p>{/foreach}</p>
<p><br />{/if}</p>
<hr />`

**Comment by Kian987** [comment]
The [updated version](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/hooks/PromotionsArrayInEmailTemplates.php) automatically removes expired promotions from the array.
