### ISSUE TITLE
[Feature request] Possible to assign client group based on other parameters?

### ISSUE THREAD

**Issue by carlojou** [Katamaze/WHMCS-Free-Action-Hooks#4]
Hello,

Would it be possible to assign client groups based on other parameters, for example how long the client has been active for?

The following hook is based on what product they purchase, so thought it would be somewhat possible:

https://github.com/Katamaze/WHMCS-Free-Action-Hooks#client-to-group-based-on-purchased-items

Any input would be appreciated. Good work regardless :)

**Comment by Kian987** [comment]
Hi,

yes, it's possible but I'll need to code a new hook as the existing one is becoming too "fat". I'll let you know when it's ready.

**Comment by Kian987** [comment]
@carlojou the hook is ready for use. You can find all details [here](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/README.md#client-to-group-based-on-registration-date).

**Comment by carlojou** [comment]
@Kian987 Thanks so much, really appreciate your effort.

I had a look at the code and was wondering how would one do the following requirements for a group for instance:

Requirement 1: Client Registration > 100 Days (from tblclients) (This is already in the code)
Requirement 2: Client Status = Active (from tblclients) 
Requirement 3: Client Has at least one hosting account that is active for > 100 days. (from tblhosting)

If the client were to have all those requirements, we would set it to group 1 for example.

Hopefully, I got the databases correct :)

**Comment by Kian987** [comment]
The hook has been [updated](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/README.md#client-to-group-based-on-registration-date) to support your scenario.

**Comment by carlojou** [comment]
Hello Kian,

While testing out the code, I forgot that there are free products that shouldn't be counted towards the "oldestPurchase" variable, so I made this:

`<?php

/**
 * Assign Client to Group based on registration date
 *
 * @package     WHMCS
 * @copyright   Katamaze
 * @link        https://katamaze.com
 * @author      Davide Mantenuto <info@katamaze.com>
 */

use WHMCS\Database\Capsule;

add_hook('DailyCronJob', 1, function($vars)
{
    // Define group/product pairs. Instructions provided below
    // https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/README.md#client-to-group-based-on-registration-date
    $groups['1'] = '2562';
    $groups['3'] = '2031';
    $groups['4'] = '2552';

    $activeCustomers = true;
    $oldestPurchase = 401;
    $freeproductID = 100;

    if (!$groups): return; endif;

    $filterStatus = ($activeCustomers ? ' AND status = "Active"' : false);

    if ($oldestPurchase)
    {
        foreach (Capsule::select(Capsule::raw('SELECT t1.id FROM tblclients AS t1 LEFT JOIN tblhosting AS t2 ON t1.id = t2.userid LEFT JOIN tbldomains AS t3 ON t1.id = t3.userid WHERE DATEDIFF(CURDATE(), t2.regdate) >= "' . $oldestPurchase . '" AND t2.packageid != "' . $freeproductID . '" GROUP BY t1.id')) as $v)
        {
            $filterPurchase[] = $v->id;
        }

        if ($filterPurchase)
        {
            $filterPurchase = ' AND id IN (\'' . implode('\',\'', $filterPurchase) . '\')';
        }
    }

    foreach ($groups as $groupID => $days)
    {
        Capsule::table('tblclients')->whereRaw('DATEDIFF(CURDATE(), datecreated) >= "' . $days . '"' . $filterStatus . $filterPurchase)->update(['groupid' => $groupID]);
    }
});`

I removed the domain part and replaced it with an "AND" function comparing it to the freeproductID. Hopefully it's fine, let me know if there are any issues with it. I was thinking about putting the variable "FreeproductID" with multiple values but not too experienced with Capsule so don't know how to insert the array into there.

I do want to again thank you for your time. It's quite amazing how you freely contribute towards WHMCS and its community.

Thank you!

**Comment by Kian987** [comment]
I [updated](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/README.md#client-to-group-based-on-registration-date) the script to include new options:

* `$ignoreDomains` set `true` to ignore domain purchases when `$oldestPurchase` is in use
* `$ignoreProducts` array of product IDs to ignore when `$oldestPurchase` is in use

In your specific case you should use the following settings:

```
$activeCustomers = true;
$oldestPurchase = 100;
$ignoreDomains = true;
$ignoreProducts = array('100');
```
