### ISSUE TITLE
[Feature Request] Client to Group based on active registered domains

### ISSUE THREAD

**Issue by Kian987** [Katamaze/WHMCS-Free-Action-Hooks#6]
Based on [this suggestions](https://katamaze.com/blog/32/whmcs-free-hook-module#comment-9), we're going to create an action hook to move customers to groups based on the number of active domains in their accounts.

**Comment by Kian987** [comment]
The hook is [ready for use](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/README.md#client-to-group-based-on-registered-domains).

**Comment by Remitur** [comment]
Great hook!
I suggest to add into a log-write function, to record the change ("user id# 1234 has been automatically assigned to price slab 2", or something like that...
It's not trivial such as add a localApi call to LogActivity, but I guess it require also a full rewrite to the query that does the job (that currently check and rewrite the grouped for every single user, even if there's no change... to do it, it's also necessary to retrieve from db current groupid, and rewrite it only if it's changed...)

**Comment by Kian987** [comment]
I updated the script to log changes to clients group. You can find a preview at the very end of [this section](https://github.com/Katamaze/WHMCS-Free-Action-Hooks/blob/master/README.md#client-to-group-based-on-registered-domains).
